name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - run: dart pub get
      - run: dart format . --set-exit-if-changed
      - run: dart analyze
      - run: dart test
